# Generated by Django 5.2.16 on 2026-07-28 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('number', models.PositiveIntegerField(help_text='Numéro affiché (01..35), 0 pour les projets')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('course', 'Cours'), ('project', 'Projet')], default='course', max_length=20)),
                ('icon', models.CharField(default='📗', max_length=16)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('estimated_minutes', models.PositiveIntegerField(default=60)),
                ('difficulty', models.PositiveSmallIntegerField(default=1, help_text='1 à 5')),
                ('notebook_path', models.CharField(blank=True, max_length=255)),
                ('colab_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('prompt', models.TextField()),
                ('explanation', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#38bdf8', max_length=20)),
                ('accent', models.CharField(default='#0ea5e9', max_length=20)),
                ('icon', models.CharField(default='📘', max_length=16)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('prerequisites', models.TextField(blank=True)),
                ('estimated_weeks', models.PositiveIntegerField(default=10)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Diagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Hash stable du bloc source', max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('fmt', models.CharField(choices=[('mermaid', 'Mermaid'), ('svg', 'SVG inline'), ('ascii', 'ASCII (à convertir)')], default='ascii', max_length=12)),
                ('mermaid', models.TextField(blank=True)),
                ('svg', models.TextField(blank=True)),
                ('source_ascii', models.TextField(blank=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='catalog.module')),
            ],
            options={
                'ordering': ['module__order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, help_text='a, b, c, d', max_length=8)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='catalog.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Quiz de fin de module', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pass_score', models.PositiveSmallIntegerField(default=70, help_text='Score en %')),
                ('xp_reward', models.PositiveIntegerField(default=100)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='catalog.module')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='catalog.quiz'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('kind', models.CharField(default='doc', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='catalog.module')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='catalog.track'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField(blank=True)),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('estimated_minutes', models.PositiveIntegerField(default=8)),
                ('xp_reward', models.PositiveIntegerField(default=20)),
                ('has_code', models.BooleanField(default=False)),
                ('has_diagram', models.BooleanField(default=False)),
                ('has_exercise', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='catalog.module')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('module', 'slug')},
            },
        ),
    ]
