# Generated by Django 5.2.16 on 2026-07-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="kind",
            field=models.CharField(
                choices=[("mcq", "QCM"), ("open", "Question ouverte")],
                default="mcq",
                max_length=8,
            ),
        ),
    ]
