# Generated by Django 5.2.16 on 2026-07-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_question_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagram",
            name="data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Structure pour tree/stack/panels"
            ),
        ),
        migrations.AlterField(
            model_name="diagram",
            name="fmt",
            field=models.CharField(
                choices=[
                    ("mermaid", "Mermaid (flux)"),
                    ("svg", "SVG inline"),
                    ("tree", "Arborescence"),
                    ("stack", "Pile de couches"),
                    ("panels", "Panneaux comparatifs"),
                    ("ascii", "ASCII (à convertir)"),
                ],
                default="ascii",
                max_length=12,
            ),
        ),
    ]
