# Generated by Django 5.2.16 on 2026-07-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_diagram_data_alter_diagram_fmt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagram",
            name="fmt",
            field=models.CharField(
                choices=[
                    ("mermaid", "Mermaid (flux)"),
                    ("svg", "SVG inline"),
                    ("tree", "Arborescence"),
                    ("stack", "Pile de couches"),
                    ("panels", "Panneaux comparatifs"),
                    ("callout", "Encadré titré"),
                    ("ascii", "ASCII (à convertir)"),
                ],
                default="ascii",
                max_length=12,
            ),
        ),
    ]
